### ISSUE TITLE
Issues pushing to Loki Distributed

### ISSUE THREAD

**Issue by Sam-Sundar** [Julien-R44/pino-loki#24]
We've moved away from Loki Simple Scalable to [Loki-Distributed](https://artifacthub.io/packages/helm/grafana/loki-distributed)  which has below components. 

```
 kubectl get svc -n loki
NAME                                       TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)                      AGE
loki-distributed-compactor                 ClusterIP   10.72.7.5      <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-distributor               ClusterIP   10.72.1.114    <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-gateway                   ClusterIP   10.72.10.158   <none>        80/TCP                       5d3h
loki-distributed-ingester                  ClusterIP   10.72.5.141    <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-ingester-headless         ClusterIP   None           <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-memberlist                ClusterIP   None           <none>        7946/TCP                     5d3h
loki-distributed-querier                   ClusterIP   10.72.5.210    <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-querier-headless          ClusterIP   None           <none>        3100/TCP,9095/TCP            5d3h
loki-distributed-query-frontend            ClusterIP   10.72.6.150    <none>        3100/TCP,9095/TCP,9096/TCP   5d3h
loki-distributed-query-frontend-headless   ClusterIP   None           <none>        3100/TCP,9095/TCP,9096/TCP   5d3h
loki-distributed-query-scheduler           ClusterIP   None           <none>        3100/TCP,9095/TCP            5d3h
```

Here `loki-distributed-gateway` is a nginx proxy which sends requests based on url subpath. We tried to configure pino to push to `loki-distributed-gateway` , `loki-distributed-ingester` & `loki-distributed-distributor` and we are getting below error
`Got error when trying to send log to Loki: Response code 400 (Bad Request)`. 

If we add [/loki/api/v1/push](https://grafana.com/docs/loki/latest/reference/api/#push-log-entries-to-loki) to the endpoint, pino starts throwing 404 like below.
`Got error when trying to send log to Loki: Response code 404 (Not Found)`

PS: Also attaching my promtail config, which is able to push to Loki Distributed without any issues. 
`promtail.yaml`
```yaml
server:
  log_level: info
  http_listen_port: 3101
  

clients:
  - url: http://loki-distributed-gateway.loki/loki/api/v1/push

positions:
  filename: /run/promtail/positions.yaml

scrape_configs:
  # See also https://github.com/grafana/loki/blob/master/production/ksonnet/promtail/scrape_config.libsonnet for reference
  - job_name: kubernetes-pods
    pipeline_stages:
      - cri: {}
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels:
          - __meta_kubernetes_pod_controller_name
        regex: ([0-9a-z-.]+?)(-[0-9a-f]{8,10})?
        action: replace
        target_label: __tmp_controller_name
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_name
          - __meta_kubernetes_pod_label_app
          - __tmp_controller_name
          - __meta_kubernetes_pod_name
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: app
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_instance
          - __meta_kubernetes_pod_label_release
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: instance
      - source_labels:
          - __meta_kubernetes_pod_label_app_kubernetes_io_component
          - __meta_kubernetes_pod_label_component
        regex: ^;*([^;]+)(;.*)?$
        action: replace
        target_label: component
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - namespace
        - app
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - action: replace
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
      - action: replace
        regex: true/(.*)
        replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_annotationpresent_kubernetes_io_config_hash
        - __meta_kubernetes_pod_annotation_kubernetes_io_config_hash
        - __meta_kubernetes_pod_container_name
        target_label: __path__
  
  

limits_config:
```

CC: @Gab-Metzger
